=== Stanishevski/AT2019-03-12/src/by/it/okoyro/at15/sites.dtd
<?xml version="1.0" encoding="utf-8" ?>
		<!ELEMENT sites (site)+>
		<!ELEMENT site (pages)>
		<!ATTLIST site url PCDATA #REQUIRED>
		<!ELEMENT pages (page)+>
		<!ELEMENT page (uri,elements)>
		<!ATTLIST page title PCDATA #REQUIRED>
		<!ELEMENT uri (#PCDATA) >
		<!ELEMENT elements (element)+>
		<!ELEMENT element (#PCDATA)>
		<!ATTLIST element name PCDATA #REQUIRED>

=== Stanishevski/AT2019-03-12/src/by/it/okoyro/at15/sites+dtd.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE sites SYSTEM "sites.dtd">
<sites>
	<site url="http:/it.by">
		<pages>
			<page title="Main page">
				<uri>
				/index
				</uri>
				<elements>
					<element name="head">
						head for main
					</element>
					<element name="body">
						text for body
					</element>
				</elements>
			</page>
		</pages>
		<pages>
			<page title="Login page">
				<uri>
				/index login
				</uri>
				<elements>
					<element name="head">
						head for main
					</element>
					<element name="form">
						form login
					</element>
				</elements>
			</page>
		</pages>
	</site>
	<site url="http:/ya.ru">
		<pages>
			<page title="Index page">
				<uri>
				/index
				</uri>
				<elements>
					<element name="head">
						search yandex
					</element>
					<element name="form">
						search form
					</element>
				</elements>
			</page>
		</pages>
		<pages>
			<page title="Result page">
				<uri>
				/result
				</uri>
				<elements>
					<element name="head">
						Search result Yandex
					</element>
					<element name="content">
						content
					</element>
				</elements>
			</page>
		</pages>
	</site>
</sites>
