=== Stanishevski/AT2019-03-12/src/by/it/stanishevski/at15/sites.dtd
<?xml version="1.0" encoding="utf-8" ?>
        <!ELEMENT sites (site)+>
        <!ELEMENT site (pages)>
        <!ATTLIST site url PCDATA #REQUIRED>
        <!ELEMENT pages (page)+>
        <!ELEMENT page (name,elements)>
        <!ATTLIST page title PCDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT elements (element)+>
        <!ELEMENT element (#PCDATA)>
        <!ATTLIST element element_id PCDATA #REQUIRED>

=== Stanishevski/AT2019-03-12/src/by/it/stanishevski/at15/sites+dtd.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE sites SYSTEM "sites.dtd" >
<sites>
    <site url="http://pvt.by">
        <pages>
            <page title="Main">
                <name>Index</name>
                <elements>
                    <element element_id="Menu">Menu page </element>
                    <element element_id="About...">About us page</element>
                    <element element_id="Counter">Visitors counter page</element>
                </elements>
            </page>
            <page title="Contacts">
                <name>Contact page</name>
                <elements>
                    <element element_id="City">Minsk</element>
                    <element element_id="Street">Skryganova 14</element>
                    <element element_id="Floor">5</element>
                </elements>
            </page>
        </pages>
    </site>
    <site url="http://fluke.com">
        <pages>
            <page title="Home">
                <name>Index</name>
                <elements>
                    <element element_id="Measurment">Catalog of equipments page</element>
                    <element element_id="Deallers">Dealler adressess page</element>
                    <element element_id="Price">Price-list page  </element>
                </elements>
            </page>
            <page title="Support">
                <name>Support page</name>
                <elements>
                    <element element_id="Soft">Software download page</element>
                    <element element_id="Instruction">Manuals</element>
                    <element element_id="Repair">Service center adressess page </element>
                </elements>
            </page>
        </pages>
    </site>
</sites>
