=== Stanishevski/AT2019-03-12/src/by/it/udalyou/at15/sites.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema  xmlns="http://www.w3.org/2001/XMLSchema"
         targetNamespace="http://bean.at15.udalyou.it.by"
         xmlns:tns="http://bean.at15.udalyou.it.by"
         elementFormDefault="qualified">
    <element name="sites">
        <complexType>
            <sequence>
                <element name="site"
                         type="tns:typeSite"
                         minOccurs="1"
                         maxOccurs="unbounded"></element>
            </sequence>
        </complexType>
    </element>
    <complexType name="typeSite">
        <sequence>
            <element name="pages"
                     type="tns:typePages">
            </element>
        </sequence>
        <attribute name="url" type="string"/>
    </complexType>
    <complexType name="typePages">
        <sequence>
            <element name="page" type="tns:typePage" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="typePage">
        <sequence>
            <element name="uri" type="string"/>
            <element name="elements"
                     type="tns:typeElements"
                     maxOccurs="unbounded"/>
         </sequence>
    <attribute name="title" type="string"/>
    </complexType>
    <complexType name="typeElements">
        <sequence>
            <element name="typeElement"
                     type="tns:typeElement"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="typeElement">
        <simpleContent>
            <extension base="string">
            <attribute name="name" type="string" use="required"/>
            </extension>
        </simpleContent>
    </complexType>
</schema>

=== Stanishevski/AT2019-03-12/src/by/it/udalyou/at15/sites+xsd.xml
<?xml version="1.0" encoding="utf-8" ?>
<sites xmlns="http://bean.at15.udalyou.it.by"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://bean.at15.udalyou.it.by sites.xsd
http://bean.at15.udalyou.it.by ">
    <site url="http://it.by">
        <pages>
            <page title="Main page">
                <uri>/index</uri>
                <elements>
                    <typeElement name="head">
                        head for main
                    </typeElement>
                    <typeElement name="body">
                        text for body
                    </typeElement>
                </elements>
            </page>
            <page title="Login page">
                <uri>/login</uri>
                <elements>
                    <typeElement name="head">
                        head for main
                    </typeElement>
                    <typeElement name="form">
                        form login
                    </typeElement>
                </elements>
            </page>
        </pages>
    </site>
    <site url="http://ya.ru">
        <pages>
            <page title="Index page">
                <uri>/index</uri>
                <elements>
                    <typeElement name="head">
                        Search yandex
                    </typeElement>
                    <typeElement name="form">
                        search form
                    </typeElement>
                </elements>
            </page>
            <page title="Search result page">
                <uri>/result</uri>
                <elements>
                    <typeElement name="head">
                        Search result Yandex
                    </typeElement>
                    <typeElement name="content">
                        some content
                    </typeElement>
                </elements>
            </page>
        </pages>
    </site>
</sites>
